### ISSUE TITLE
Webpack tanimi

### ISSUE THREAD

**Issue by burakcan** [jargonist/jargon.ist#28]
https://jargon.ist/webpack

cok dogru degil gibi geldi bana. Ne yazsak onu da tam cozemedim ama birisinin fikri varsa duzenleyelim.

**Comment by Berat** [comment]
Kısa olacak ama modül paketleyicisi denilebilir aslında.

**Comment by burakcan** [comment]
Buna cozuldu diyebiliriz sanirim.
