### ISSUE TITLE
Immutable ornegi kafa karisikligi yaratabilir

### ISSUE THREAD

**Issue by burakcan** [jargonist/jargon.ist#29]
https://jargon.ist/immutable

Burada verilen `const` ornegi kafa karisikligi(immutable reference vs data structure) yaratabilir. Ornek olarak immutable bi data structure vermek daha dogru olabilir. Ya da ikisi icin ayri ornekler koyulabilir.

**Comment by alpcanaydin** [comment]
78ad7a6e ile bir ornek daha ekledim @burakcan.
