### ISSUE TITLE
Örneklerde Kullanılan Dil

### ISSUE THREAD

**Issue by ogirginc** [jargonist/jargon.ist#39]
Açıklamadan sonra verilen örneklerde sadece JS mi kullanılabiliyor? Yoksa diğer dillerde de örnek verilmesine müsade var mı?

**Comment by alpcanaydin** [comment]
Merhaba, herhangi bir dil sinirlamasi bulunmuyor. Ben sadece kisisel olarak genel konularda javascript kullanmaya calisiyorum daha genel gecer bir dil oldugu icin. Siz istediginiz dilde katkida bulunabilirsiniz.

**Comment by ogirginc** [comment]
Teşekkürler 😊
