### ISSUE TITLE
Safari has blank page issues for sub pages

### ISSUE THREAD

**Issue by gokmen** [jargonist/jargon.ist#55]
Most of the sub pages not rendering on Safari both on desktop and mobile. eg. https://jargon.ist/dizin

**Comment by ogirginc** [comment]
@gokmen sub pages'dan kastın nedir? Ben ne Safari'de [Version 11.1 (13605.1.33.1.2)] ne de Safari Technology Preview'de [Release 53 (Safari 11.2, WebKit 13606.1.11.2)] bir hata gördüm.

**Comment by alpcanaydin** [comment]
Sanirim service worker yuzunden oluyor. #59 ile kaldirdim, cmd+shift+r ile tekrar bakma sansin var mi @gokmen? Service worker cache'nin ortadan kalkmasi 24 saati buluyor.

**Comment by gokmen** [comment]
Evet duzelmis gozukuyor, macos uzerinden bir hata veriyordu da mobilden
goremiyorum simdilik. Masaustune gecince onu da eklerim. Simdilik
kapatilabilir bu, ellerinize saglik.
