### ISSUE TITLE
CreatePages Unexpected Token Hatası

### ISSUE THREAD

**Issue by nihatakin** [jargonist/jargon.ist#86]
Merhaba,

Sabah npm registery sorunu alıyordum amazon set ettim sorun düzeldi şimdi ise  Unexpected token hatası almaktayım yardımcı olabilirmisiniz.

![image](https://user-images.githubusercontent.com/6771287/39994426-f67a0580-5781-11e8-98cf-7aa2f64d0ab3.png)

**Comment by alpcanaydin** [comment]
Merhaba node.js versiyonu ile ilgili bir problem olabilir, en az 9 versiyonu ile deneyebilir misiniz?
