### ISSUE TITLE
Neden Gatsby kullanildigi hakkinda soru

### ISSUE THREAD

**Issue by omermindivanli** [jargonist/jargon.ist#89]
Merhabalar Gatsby kullanmanizin özel bir amaci var miydi? Yoksa yeni teknolojileri ogrenmek istediginizde boyle projeler mi yaparak ogrenmeyi tercih ediyosunuz? Iyi calismalar...

**Comment by alpcanaydin** [comment]
Merhaba,

Birinci olarak dediginiz gibi yeni bir arac kullanmak istememden dolayi Gatsby'i sectim. Ikinci olarak da, hizlica markdown dosyalarindan React sayfalari yarattigi icin bu projede altyapi olarak kullaniliyor.
